### ISSUE TITLE
Дубликат

### ISSUE THREAD

**Issue by Xandir150** [gusev-p/simple-1c#8]
System.InvalidOperationException: property [Регистратор] for table [РегистрБухгалтерии.Хозрасчетный.Субконто0] already exist
   в Simple1C.Impl.Sql.SchemaMapping.TableMapping..ctor(String queryTableName, String dbName, TableType type, PropertyMapping[] properties) в c:\Work\simple-1c\Simple1C\Impl\Sql\SchemaMapping\TableMapping.cs:строка 49

**Comment by ivan816** [comment]
I've confirmed this bug. It'll be fixed soon

**Comment by ivan816** [comment]
Bug is fixed

**Comment by ivan816** [comment]
New version is available in NuGet
